//
//  HomePresenter.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentGit(response: Home.Git.Response)
    func presentError(error: Home.Git.GitError)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    // MARK: presentGit

    func presentGit(response: Home.Git.Response) {
        var representableList = [Home.Git.ViewModeRepresentable]()

        for gitModel in response.gitModel.items {
            let git = Home.Git.ViewModeRepresentable(
                title: gitModel.name,
                description: gitModel.description,
                likes: "\(gitModel.forks)",
                shared: "\(gitModel.watchers)",
                avatar: gitModel.owner.avatarURL,
                userName: gitModel.name,
                surName: gitModel.fullName)
            representableList.append(git)
        }

        let viewModel = Home.Git.ViewModel(gitRepresentable: representableList)
        viewController?.displayGit(viewModel: viewModel)
    }

    func presentError(error: Home.Git.GitError) {
        viewController?.displayError(viewModel: error)
    }

}
