//
//  HomeWorker.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


class HomeWorker {
    func doWorkGit(request: Home.Git.Request) {
        let params = ["q":"language:Java","sort":"stars","page":"\(request.id  )"].queryFormat()
        let requestable = WorkerRequestable(queryString: params)
        let req: HTTRequest<GitModel> = HTTRequest(requestable: requestable)
        req.get(success: { response in
            guard let gitModel = response else {
                request.completion(.failure(NSError(domain: "Erro na requisição da Tabela", code: 500, userInfo:nil)))
                return
            }
            request.completion(.success(gitModel))
            return
        }) { (error) in
            request.completion(.failure(error))
        }
    }
    
}
struct WorkerRequestable: HTTPRequestable {
    var queryString: String
    var path: String {
        return "search/repositories?" + queryString
    }
    var url: URL {
        return URL(string: environment.host+path)!
    }
}

