//
//  HomeRouter.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeTosegueDetail(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    // MARK: Routing
    func routeTosegueDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as? DetailViewController
            if let router = destinationVC?.router,
                let routerDataStore = router.dataStore,
                let dataStore = dataStore {
                var destinationDS = routerDataStore
                passDataTosegueDetail(source: dataStore, destination: &destinationDS)
            }
        }
    }
    // MARK: Passing data
    func passDataTosegueDetail(source: HomeDataStore, destination: inout DetailDataStore) {
        destination.fullName = source.fullName
    }
}
