//
//  HomeModels.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases
    enum Git {
        struct Request {
            let id: String
            let completion: (_ detail: Result<GitModel, Error>) -> Void
        }
        struct Response {
            let gitModel:GitModel
        }
        struct ViewModel {
            let gitRepresentable: [ViewModeRepresentable]
        }
        
        struct ViewModeRepresentable: GitCellRepresentable {
            var title: String?
            var description: String?
            var likes: String?
            var shared: String?
            var avatar: String?
            var userName: String?
            var surName: String?
        }
        
        struct GitError {
            let erro: Error
        }
    }
}
