//
//  HomeWorker.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker {

    func doWorkGit(request: Home.Git.Request, completion: @escaping (Result<GitModel, Error>) -> Void) {
        let params = ["q": "language:Java", "sort": "stars", "page": "\(request.identify)"].queryFormat()
        let requestable = WorkerRequestable(queryString: params)
        let req: HTTRequest<GitModel> = HTTRequest(requestable: requestable)

        req.getNew { (result) in
            switch result {
            case .success(let model):
                completion(.success(model))
                print(model)
            case .failure(let erro):
                completion(.failure(NSError(domain: "Erro na requisição da Tabela", code: 500, userInfo: nil)))
                print(erro)
            }
        }
    }
}
struct WorkerRequestable: HTTPRequestable {
    var queryString: String
    var path: String {
        "search/repositories?" + queryString
    }
    var url: URL {
        URL(string: environment.host + path)!
    }
}
