//
//  HomeInteractor.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func doInteractorGit(id: String)
}

protocol HomeDataStore {
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?

    // MARK: Do something

    func doInteractorGit(id: String) {
        worker = HomeWorker()
        let req = Home.Git.Request(id: id) { result in
            switch result {
            case .success(let response):
                let gitModel = Home.Git.Response(gitModel: response)
                self.presenter?.presentGit(response: gitModel)
                break
            case .failure(let response):
                let error = Home.Git.GitError(erro: response)
                self.presenter?.presentError(error: error)
                break
            }
        }
        worker?.doWorkGit(request: req)
    }
}
