//
//  DetailInteractor.swift
//  GitProject
//
//  Created by anunes on 09/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func doSomething(request: Detail.Something.Request)
}

protocol DetailDataStore {
    //var name: String { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?
    var worker: DetailWorker?
    
    // MARK: Do something
    
    func doSomething(request: Detail.Something.Request) {
        worker = DetailWorker()
        worker?.doSomeWork()
        
        let response = Detail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
