//
//  DetailModels.swift
//  GitProject
//
//  Created by anunes on 09/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases
    enum PullsRequest {
        struct Request {
            let fullName: String
        }
        struct Response {
            let pulls: [Pull]
        }
        struct ViewModel {
            let pullRepresentable: [ViewModelRepresentable]
        }
        struct ViewModelRepresentable: PullRepresentable {
            var title: String?
            var avatar: String?
            var fullName: String?
        }
        struct GitError {
            let erro: Error
        }
    }
}
