//
//  DetailPresenter.swift
//  GitProject
//
//  Created by anunes on 09/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentPulls(response: Detail.PullsRequest.Response)
    func presenterErro(error: Detail.PullsRequest.GitError)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    // MARK: Do something    
    func presentPulls(response: Detail.PullsRequest.Response) {
        let viewModel = Detail.PullsRequest.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }

    func presenterErro(error: Detail.PullsRequest.GitError){
        
    }
}
