//
//  DetailWorker.swift
//  GitProject
//
//  Created by anunes on 09/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    func doPullRequest(request: Detail.PullsRequest.Request, completion: @escaping (Result<Pulls, Error>) -> Void) {
        let queryString = "\(request.fullName)/pulls"
        let requestable = WorkerDetailRequestable(queryString: queryString)
        let req: HTTRequest<Pulls> = HTTRequest(requestable: requestable)

        req.get { (result) in
            switch result{
            case .success(let model):
                completion(.success(model))
            case .failure(let error):
                completion(.failure(error))
            }
        }
    }
}

struct WorkerDetailRequestable: HTTPRequestable {
    var path: String {
        "repos/"
    }
    var queryString: String
    var url: URL {
        URL(string: environment.host + path)!
    }
}
