//
//  HomeWorker.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GithubAPI


class HomeWorker
{

    func doFake(request: Home.Git.Request){
        let mock = FakeService()
        guard let response = mock.getMock(model: GitModel.self, file: mock.getData(name: "GitModel")) else {
            request.completion(.failure(NSError(domain: "Home Erro", code: 500, userInfo: nil)))
            return
        }
        request.completion(.success(response))
    }

    func doSearchGit(){
        SearchAPI().searchRepositories(q: "qwer", page: 1, per_page: 100) { (response, error) in
            if let response = response {
                 print(response)
            } else {
                print(error ?? "")
            }
        }
    }
    func doWorkGit(request: Home.Git.Request){
        let requestable = WorkerRequestable()
        let req: HTTRequest<GitModel> = HTTRequest(requestable: requestable)
        req.get(success: { response in
            guard let gitModel = response else{
                request.completion(.failure(NSError(domain: "Erro na requisição da Tabela", code: 500, userInfo:nil)))
                return
            }
            request.completion(.success(gitModel))
            return
        }) { (error) in
            request.completion(.failure(error))
        }

    }
    
}
struct WorkerRequestable: HTTPRequestable{
    //https://github.com/settings/connections/applications/Iv1.fec63711a2bc193e
    var params: [String : Any]?
    var path: String {
        return "search/repositories?q=language:Java&sort=stars&page=1"
    }
    var url: URL {
        return URL(string: environment.host)!
    }
}

