//
//  HomeInteractor.swift
//  Git
//
//  Created by anunes on 02/03/20.
//  Copyright (c) 2020 Santander Tecnologia. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
 func doSomething(id: String)
}

protocol HomeDataStore
{
  //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func doSomething(id: String) {

        API.getUsers { result in

            print(result)

        }
//        worker = HomeWorker()
//        let req = Home.Git.Request(id: id) { result in
//            switch result{
//            case .success(let response):
//                 let gitModel = Home.Git.Response(gitModel: response)
//                self.presenter?.presentSomething(response: gitModel)
//                break
//            case .failure(let response):
//                let error = Home.Git.GitError(erro: response)
//                self.presenter?.presentError(error: error)
//                break
//            }
//        }
//        worker?.doFake(request: req)

//        worker?.doSearchGit()
    }
}
